apiVersion: v1
kind: Pod
metadata:
  name: my-pod4
  namespace: azure-vote-04
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 8080
    env:
    - name: POD_NAME
      value: "my_pod"
    - name: PORT
      value: "8080"
    - name: REDIS
      valueFrom:
        secretKeyRef:
          name: redis-secret 
          key: "attribute.primary_connection_string"
          optional: false
    - name: REDIS_PWD
      valueFrom:
        secretKeyRef:
          name: redis-secret 
          key: "attribute.primary_access_key"
          optional: false