apiVersion: v1
kind: Namespace
metadata:
  name: azure-vote-04
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: ${APP_NAME}
  namespace: azure-vote-04
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
---
apiVersion: cache.azure.upbound.io/v1beta1
kind: RedisCache
metadata:
  name: ${APP_NAME}-redis
  namespace: azure-vote-04
spec:
  forProvider:
    capacity: 0
    enableNonSslPort: true
    minimumTlsVersion: "1.2"
    family: C
    location: West Europe
    redisConfiguration:
      - maxmemoryDelta: 10
        maxmemoryPolicy: allkeys-lru
    redisVersion: "6"
    resourceGroupNameRef:
      name: ${APP_NAME}
    skuName: Basic
  writeConnectionSecretToRef:
    name: redis-secret
    namespace: azure-vote-04
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: azure-vote-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: ${IMAGE_COMPLETE_NAME}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          valueFrom:
            secretKeyRef:
              name: redis-secret 
              key: endpoint
              optional: false
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis-secret 
              key: primaryKey
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: azure-vote-04
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front
